name: ci

on: [push]

jobs:
  build:
    name: all
    runs-on: ubuntu-latest
    steps:
      - name: setup
        uses: actions/setup-go@v1
        with:
          go-version: 1.14
        id: go
      - name: checkout
        uses: actions/checkout@v1
      - name: cache
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: install lint
        run: curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.30.0
      - name: lint
        run: $(go env GOPATH)/bin/golangci-lint run
      - name: test
        run: go test ./... -v
      - name: build
        env:
          goos: "linux"
          goarch: "amd64"
        run: |
          mkdir dist
          GOODS=$goos GOARCH=$goarch go build -v -o dist/book_service-$goos-$goarch .
          ls -l dist
      - name: upload artifact
        env:
          goos: "linux"
          goarch: "amd64"
        uses: actions/upload-artifact@v1
        with:
          name: binary
          path: dist/book_service-${{ goos }} -${{ goarch }}
